TrajectoryPlannerROS:

  holonomic_robot: true
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -0.1
  min_in_place_vel_theta: 0.4
  escape_vel: -0.2

  sim_time: 2.0
  controller_frequency: 10.0

  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.1
  heading_lookahead: 0.5
  heading_scoring_timestep: 0.8
